<?php
require_once dirname(__FILE__) . '/../../public/h_tools.php';

/**
 * Test class for CFormulaParser.
 * Generated by PHPUnit on 2010-11-30 at 01:24:58.
 */
class CFormulaParserTest extends PHPUnit_Framework_TestCase
{
	public function test()
	{
		$p = new StdClass;
		$p->price = 12.34;
		$fp = new CFormulaParser;
		var_dump($fp->GetFormula($p, '{{price}} + 5'));
	}
}

?>
