<?php
require_once dirname(__FILE__) . '/../../../../public/modules/admin/admin.php';

/**
 * Test class for ModAdmin.
 * Generated by PHPUnit on 2010-11-30 at 00:54:59.
 */
class ModAdminTest extends PHPUnit_Framework_TestCase
{
	public function test()
	{
		$m = new ModAdmin;
		$m->Link();
		$m->Prepare();
		$m->Get();
	}
}

?>
